import logging

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.pipeline.factory import build_pipeline
from app.auth.dependencies import get_current_admin_user
from app.api.deps import (
    get_user_repository,
    get_pipeline_run_repository,
    get_insight_repository,
)
from app.data.repositories.base import (
    UserRepositoryBase,
    PipelineRunRepositoryBase,
    InsightRepositoryBase,
)
from app.api.schemas import (
    RunPipelineRequest,
    PipelineRunResponse,
    UpgradeRoleRequest,
    DowngradeRoleRequest,
    DowngradeRoleResponse,
    RoleUpdateResponse,
    UpgradePlanRequest,
    PlanUpdateResponse,
    DowngradePlanRequest,
    DowngradePlanResponse,
    InsightResponse,
)
from app.data.models.users import User
from app.core.database import get_db
from app.utils.redis_lock import acquire_lock, release_lock, GLOBAL_PIPELINE_LOCK_KEY


logger = logging.getLogger(__name__)

router = APIRouter(prefix="/admin", tags=["Admin"])


@router.post(
    "/run",
    response_model=PipelineRunResponse,
    status_code=status.HTTP_200_OK,
    summary="Execute a data pipeline (Admin only)",
    description="Trigger a pipeline run. Only accessible by admin users.",
)
async def run_pipeline(
    request: RunPipelineRequest,
    db: AsyncSession = Depends(get_db),
    admin_user: User = Depends(get_current_admin_user),
    pipeline_run_repo: PipelineRunRepositoryBase = Depends(get_pipeline_run_repository),
):
    # 1. Attempt to acquire the GLOBAL pipeline lock (Fail Fast)
    if not await acquire_lock(GLOBAL_PIPELINE_LOCK_KEY, ttl=600):
        logger.warning(
            f"Global pipeline lock held. Rejecting admin pipeline run request for admin {admin_user.id}."
        )
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="The system is currently processing another intensive query. Please try again in a moment.",
        )

    # 2. Create audit record
    pipeline_run = await pipeline_run_repo.create_run(user_id=str(admin_user.id))
    pipeline = None

    try:
        # 3. Build and Execute Pipeline
        logger.info(
            f"Admin {admin_user.id} starting pipeline for query: {request.query}"
        )
        pipeline = build_pipeline(db=db)

        # Note: Returns a dict containing 'insight_id' on success
        pipeline_result = await pipeline.run(request.query, user_id=str(admin_user.id))

        # Check if the pipeline returned an error instead of success
        if "error" in pipeline_result:
            raise RuntimeError(pipeline_result["error"])
        
        insight_id_str = pipeline_result.get("insight_id")

        # 4. Update Audit Record on Success
        await pipeline_run_repo.update_run_status(
            run_id=str(pipeline_run.id),
            insight_id=insight_id_str,
            status="success"
        )

        logger.info(
            f"Admin {admin_user.id} successfully ran pipeline for query: {request.query}"
        )

        return PipelineRunResponse(
            message=f"Pipeline executed successfully for query: {request.query}",
            query=request.query,
            status="success",
        )
    except Exception as e:
        # 5. Update Audit Record on Failure
        await pipeline_run_repo.update_run_status(
            run_id=str(pipeline_run.id), 
            status="failed", 
            error=str(e)
        )
        logger.error(
            f"Admin {admin_user.id} pipeline execution failed: {e}", exc_info=True
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Pipeline execution failed",
        )
    finally:
        # 6. Ensure pipeline resources are cleaned up AND global lock is ALWAYS released
        if pipeline and hasattr(pipeline, "close"):
            await pipeline.close()

        await release_lock(GLOBAL_PIPELINE_LOCK_KEY)


@router.get(
    "/insights/latest",
    response_model=InsightResponse,
    summary="Get the absolute latest system-wide insight (Admin only)",
    description="Fetch the most recent insight generated by the system, regardless of user.",
)
async def get_system_latest_insight(
    admin_user: User = Depends(get_current_admin_user),
    repo: InsightRepositoryBase = Depends(get_insight_repository),
):
    logger.info(f"Admin {admin_user.id} fetching absolute latest system insight")

    # Uses the original method that ignores user_id
    insight = await repo.load_latest()

    if not insight:
        logger.warning("No insights found in database")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="No insights found in system"
        )

    logger.info(f"Successfully retrieved system latest insight with ID: {insight.id}")
    return insight


@router.post(
    "/upgrade-role",
    response_model=RoleUpdateResponse,
    status_code=status.HTTP_200_OK,
    summary="Upgrade user role (Admin only)",
)
async def upgrade_user_role(
    request: UpgradeRoleRequest,
    admin_user: User = Depends(get_current_admin_user),
    user_repo: UserRepositoryBase = Depends(get_user_repository),
):
    user = await user_repo.get_by_id(request.user_id)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="User not found"
        )

    old_role = user.role
    await user_repo.update_role(request.user_id, request.role)

    logger.info(
        f"Admin {admin_user.id} upgraded user {user.email} role from {old_role} to {request.role}"
    )

    return RoleUpdateResponse(
        message=f"User {user.email} upgraded role from {old_role} to {request.role}",
        user_id=request.user_id,
        email=user.email,
        old_role=old_role,
        new_role=request.role,
    )


@router.post(
    "/downgrade-role",
    response_model=DowngradeRoleResponse,
    status_code=status.HTTP_200_OK,
    summary="Downgrade user role (Admin only)",
)
async def downgrade_user_role(
    request: DowngradeRoleRequest,
    admin_user: User = Depends(get_current_admin_user),
    user_repo: UserRepositoryBase = Depends(get_user_repository),
):
    user = await user_repo.get_by_id(request.user_id)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="User not found"
        )

    old_role = user.role
    await user_repo.update_role(request.user_id, "user")

    logger.info(
        f"Admin {admin_user.id} downgraded user {user.email} role from {old_role} to user"
    )

    return DowngradeRoleResponse(
        message=f"User {user.email} downgraded role from {old_role} to user",
        user_id=request.user_id,
        email=user.email,
        old_role=old_role,
        new_role="user",
    )


@router.post(
    "/upgrade-plan",
    response_model=PlanUpdateResponse,
    status_code=status.HTTP_200_OK,
    summary="Upgrade user subscription plan (Admin only)",
)
async def upgrade_user_plan(
    request: UpgradePlanRequest,
    admin_user: User = Depends(get_current_admin_user),
    user_repo: UserRepositoryBase = Depends(get_user_repository),
):
    user = await user_repo.get_by_id(request.user_id)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="User not found"
        )

    old_plan = user.plan
    await user_repo.update_plan(request.user_id, request.plan)

    logger.info(
        f"Admin {admin_user.id} upgraded user {user.email} plan from {old_plan} to {request.plan}"
    )

    return PlanUpdateResponse(
        message=f"User {user.email} plan upgraded from {old_plan} to {request.plan}",
        user_id=request.user_id,
        email=user.email,
        old_plan=old_plan,
        new_plan=request.plan,
    )


@router.post(
    "/downgrade-plan",
    response_model=DowngradePlanResponse,
    status_code=status.HTTP_200_OK,
    summary="Downgrade user to free plan (Admin only)",
)
async def downgrade_user_plan(
    request: DowngradePlanRequest,
    admin_user: User = Depends(get_current_admin_user),
    user_repo: UserRepositoryBase = Depends(get_user_repository),
):
    user = await user_repo.get_by_id(request.user_id)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="User not found"
        )

    old_plan = user.plan
    await user_repo.update_subscription(
        user_id=request.user_id,
        subscription_data={
            "plan": "free",
            "subscription_status": "manual_downgrade",
        },
    )

    logger.info(
        f"Admin {admin_user.id} downgraded user {user.email} from {old_plan} to free"
    )

    return DowngradePlanResponse(
        message=f"User {user.email} downgraded to free plan",
        user_id=request.user_id,
        email=user.email,
        old_plan=old_plan,
        new_plan="free",
    )
