import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.pipeline.factory import build_pipeline
from app.data.repositories.base import InsightRepositoryBase, PipelineRunRepositoryBase
from app.api.deps import (
    get_insight_repository,
    get_pipeline_run_repository,
    get_entitlement_service,
    get_usage_service,
)
from app.auth.dependencies import get_authenticated_user  # UNIFIED DEPENDENCY
from app.api.schemas.insights import (
    InsightResponse,
    OnDemandInsightRequest,
    OnDemandInsightResponse,
)
from app.data.models.users import User
from app.monetization.usage import UsageService
from app.monetization.entitlements import EntitlementService
from app.utils.redis_lock import acquire_lock, release_lock, GLOBAL_PIPELINE_LOCK_KEY

logger = logging.getLogger(__name__)


router = APIRouter(prefix="/api/v1/insights", tags=["Insights"])


@router.get(
    "/latest",
    response_model=InsightResponse,
    summary="Get the latest generated insight for the current user",
    description="Fetch the most recent insight generated by or for the authenticated user.",
)
async def get_latest_insight(
    current_user: User = Depends(get_authenticated_user),
    repo: InsightRepositoryBase = Depends(get_insight_repository),
):
    logger.info(f"Fetching the latest insight for user {current_user.id}")

    insight = await repo.load_latest_for_user(current_user.id)

    if not insight:
        logger.warning(f"No insights found for user {current_user.id}")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No insights found for your account. Try running an on-demand query.",
        )

    logger.info(
        f"Successfully retrieved latest insight with ID: {insight.id} for user {current_user.id}"
    )
    return insight


@router.post(
    "/on-demand",
    response_model=OnDemandInsightResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate an on-demand insight",
    description="Triggers a custom query pipeline. Subject to daily quota limits. Note: This runs synchronously",
)
async def generate_on_demand_insight(
    request: OnDemandInsightRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_authenticated_user),
    entitlement_service: EntitlementService = Depends(get_entitlement_service),
    usage_service: UsageService = Depends(get_usage_service),
    pipeline_run_repo: PipelineRunRepositoryBase = Depends(get_pipeline_run_repository),
):
    # 1. Check Quota
    can_run = await entitlement_service.check_pipeline_access(current_user)
    if not can_run:
        logger.warning(f"Quota exceeded for user {current_user.id} on on-demand run")
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Daily on-demand query limit exceeded. Please upgrade your plan.",
        )

    # 2. Attempt to acquire the GLOBAL pipeline lock (Fail Fast)
    if not await acquire_lock(GLOBAL_PIPELINE_LOCK_KEY, ttl=600):
        logger.warning(
            f"Global pipeline lock held. Rejecting on-demand request for user {current_user.id}."
        )
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="The system is currently processing another intensive query. Please try again in a moment.",
        )

    # 3. Create Pipeline Run Audit Record
    pipeline_run = await pipeline_run_repo.create_run(user_id=str(current_user.id))
    start_time = datetime.now(timezone.utc)
    pipeline = None

    try:
        # 4. Build and Execute Pipeline
        logger.info(
            f"Starting on-demand pipeline for user {current_user.id}: {request.query}"
        )
        pipeline = build_pipeline(db=db)

        # Note: pipeline.run() returns the insight_id directly
        pipeline_result = await pipeline.run(request.query, user_id=str(current_user.id))

        if "error" in pipeline_result:
            raise RuntimeError(pipeline_result["error"])

        insight_id_str = pipeline_result.get("insight_id")

        # 5. Update Audit Record on Success
        duration = (datetime.now(timezone.utc) - start_time).total_seconds()
        await pipeline_run_repo.update_run_status(
            run_id=str(pipeline_run.id),
            insight_id=insight_id_str,
            status="success",
            duration_seconds=duration,
        )

        # 6. Record Usage for Quota Tracking
        await usage_service.record_run(
            str(current_user.id), metric_type="on_demand_run"
        )

        logger.info(
            f"Successfully completed on-demand pipeline {pipeline_run.id} in {duration:.2f}s"
        )

        return OnDemandInsightResponse(
            pipeline_run_id=pipeline_run.id,
            status="success",
            message="Insight generated successfully.",
            duration_seconds=duration,
        )

    except Exception as e:
        # 7. Update Audit Record on Failure
        duration = (datetime.now(timezone.utc) - start_time).total_seconds()
        await pipeline_run_repo.update_run_status(
            run_id=str(pipeline_run.id),
            status="failed",
            error=str(e),
            duration_seconds=duration,
        )

        logger.error(
            f"On-demand pipeline {pipeline_run.id} failed: {str(e)}", exc_info=True
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Pipeline execution failed. The error has been logged.",
        )
    finally:
        # 8. Ensure pipeline resources are cleaned up AND global lock is ALWAYS released
        if pipeline and hasattr(pipeline, "close"):
            await pipeline.close()
        
        await release_lock(GLOBAL_PIPELINE_LOCK_KEY)
