from fastapi import APIRouter, Depends, HTTPException, status


from app.data.repositories.base import InsightRepositoryBase
from app.api.deps import get_insight_repository
from app.api.schemas import InsightResponse


router = APIRouter(prefix="/insights", tags=["Insights"])


@router.get(
    "/latest",
    response_model=InsightResponse,
    summary="Get the latest generated insight",
    description="Fetch the most recent insight generated by the system, including its analysis and confidence metrics",
)
async def get_latest_insight(
    repo: InsightRepositoryBase = Depends(get_insight_repository),
):
    insight = await repo.load_latest()

    if not insight:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="No insights found"
        )

    return insight
