"""add pipeline_runs table for observability

Revision ID: 5ba49f3dd346
Revises: f0c83fb49c9e
Create Date: 2026-08-25 18:42:55.236365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ba49f3dd346"
down_revision: Union[str, Sequence[str], None] = "f0c83fb49c9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("insight_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["insight_id"], ["insights.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_insight_id"),
        "pipeline_runs",
        ["insight_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_runs_started_at"),
        "pipeline_runs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_runs_status"), "pipeline_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_runs_user_id"), "pipeline_runs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_runs_user_id"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_status"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_started_at"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_insight_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
