"""create insights table with uuidv7

Revision ID: a940eea9bc9d
Revises:
Create Date: 2026-07-16 19:26:19.426087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a940eea9bc9d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("query", sa.String(length=1000), nullable=False),
        sa.Column("documents_collected", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("confidence_label", sa.String(length=50), nullable=False),
        sa.Column("confidence_explanation", sa.Text(), nullable=True),
        sa.Column(
            "raw_ai_output", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insights_confidence_score"),
        "insights",
        ["confidence_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insights_created_at"), "insights", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_insights_query"), "insights", ["query"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_insights_query"), table_name="insights")
    op.drop_index(op.f("ix_insights_created_at"), table_name="insights")
    op.drop_index(op.f("ix_insights_confidence_score"), table_name="insights")
    op.drop_table("insights")
    # ### end Alembic commands ###
