"""add usage_tracking table with UPSERT support

Revision ID: f0c83fb49c9e
Revises: 2ee03e1558c0
Create Date: 2026-08-24 22:07:33.824365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0c83fb49c9e"
down_revision: Union[str, Sequence[str], None] = "2ee03e1558c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_tracking",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("metric_type", sa.String(length=50), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "usage_date", "metric_type", name="uq_usage_user_date_metric"
        ),
    )
    op.create_index(
        op.f("ix_usage_tracking_usage_date"),
        "usage_tracking",
        ["usage_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_tracking_user_id"), "usage_tracking", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_tracking_user_id"), table_name="usage_tracking")
    op.drop_index(op.f("ix_usage_tracking_usage_date"), table_name="usage_tracking")
    op.drop_table("usage_tracking")
    # ### end Alembic commands ###
