def normalize_query(query: str) -> str:
    """
    Normalize and enrich search queries for real estate intelligence.
    """

    base_keywords = [
        "Dubai real estate",
        "property market",
        "prices",
        "investment",
        "trends",
        "United Arab Emirates",
        "Abu Dhabi",
        "Capital Gains",
        "Economic growth in United Arab Emirates",
        "House prices",
        "house prices in Abu Dhabi",
        "house prices in United Arab Emirates",
        "interest rates in United Arab Emirates",
        "investment in property",
        "mortgage",
        "Price history",
        "Prices fell",
        "Prices rose",
        "Property boom",
        "Property bubble",
        "property in Abu Dhabi",
        "property in United Arab Emirates",
        "Property news",
        "Property prices",
        "Real Estate In",
        "rent",
        "rental income",
        "rental yield",
        "residential",
        "Dubai",
        "UAE",
        "Abu Dhabi",
        "Property in Dubai",
        "Dubai real estate",
        "Villas for sale",
        "Dubai Residential Property Report Q3",
        "UAE Luxury Residential Real Estate Market",
        "UAE Luxury Residential Real Estate Market Size",
        "UAE Luxury Residential Real Estate Market Share",
        "UAE Luxury Residential Real",
        "Estate Market Analysis",
        "UAE Luxury Residential Real Estate Market Trends",
        "UAE Luxury Residential Real Estate Market Report",
        "UAE Luxury Residential Real Estate Market Research",
        "UAE Luxury Residential Real Estate Industry",
        "UAE Luxury Residential Real Estate Industry Report",
        "Dubai Land",
        "Valuation",
        "Transaction",
        "DLD",
        "Service Charge",
        "Rental Index",
        "Land Status",
        "Project Status",
        "Ejari",
        "dubai property market forecast",
        "dubai real estate prices",
        "dubai property investment opportunities",
        "dubai property investment",
        "dubai housing market trends",
        "buy property in dubai",
        "dubai real estate outlook",
        "dubai real estate market analysis",
    ]

    return f"{query} " + " ".join(base_keywords)
